import { describe, it } from "vitest";
import { expect } from "chai";
import { parseYarnLock } from "../../yarn";

//
// yarn/src is yarn v1.22.22's lockfile parser, vendored and now compiled by rolldown as
// TypeScript rather than pre-built by babel. Nothing covered it before that change; these
// pin the output shape so the conversion - and any future one - is checked rather than
// assumed.
//

const SAMPLE = `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


"@babel/code-frame@^7.0.0", "@babel/code-frame@^7.10.4":
  version "7.12.13"
  resolved "https://registry.yarnpkg.com/@babel/code-frame/-/code-frame-7.12.13.tgz#dcfc826b"
  integrity sha512-HV1Cm0Q3ZrpCR93tkWOYiuYIgLxZXZFVG2VgK+MBWjUqZTundupbfx2aXarXuw5Ko==
  dependencies:
    "@babel/highlight" "^7.12.13"

lodash@^4.17.21:
  version "4.17.21"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz#679591c5"

nested-opts@^1.0.0:
  version "1.0.0"
  optionalDependencies:
    fsevents "^2.3.2"
`;

describe("yarn lockfile parser", function () {
  it("parses a v1 lockfile into name@spec entries", () => {
    expect(parseYarnLock(SAMPLE)).to.deep.equal({
      "@babel/code-frame@^7.0.0": {
        version: "7.12.13",
        resolved:
          "https://registry.yarnpkg.com/@babel/code-frame/-/code-frame-7.12.13.tgz#dcfc826b",
        integrity: "sha512-HV1Cm0Q3ZrpCR93tkWOYiuYIgLxZXZFVG2VgK+MBWjUqZTundupbfx2aXarXuw5Ko==",
        dependencies: { "@babel/highlight": "^7.12.13" }
      },
      "@babel/code-frame@^7.10.4": {
        version: "7.12.13",
        resolved:
          "https://registry.yarnpkg.com/@babel/code-frame/-/code-frame-7.12.13.tgz#dcfc826b",
        integrity: "sha512-HV1Cm0Q3ZrpCR93tkWOYiuYIgLxZXZFVG2VgK+MBWjUqZTundupbfx2aXarXuw5Ko==",
        dependencies: { "@babel/highlight": "^7.12.13" }
      },
      "lodash@^4.17.21": {
        version: "4.17.21",
        resolved: "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz#679591c5"
      },
      "nested-opts@^1.0.0": {
        version: "1.0.0",
        optionalDependencies: { fsevents: "^2.3.2" }
      }
    });
  });

  it("gives every entry a null prototype, as yarn does", () => {
    const parsed = parseYarnLock(SAMPLE) as Record<string, unknown>;
    expect(Object.getPrototypeOf(parsed)).to.equal(null);
    expect(Object.getPrototypeOf(parsed["lodash@^4.17.21"])).to.equal(null);
  });

  it("strips a byte order mark", () => {
    expect(parseYarnLock(`﻿${SAMPLE}`)).to.deep.equal(parseYarnLock(SAMPLE));
  });

  it("returns an empty object for an empty lockfile", () => {
    expect(parseYarnLock("# yarn lockfile v1\n")).to.deep.equal({});
  });

  it("merges both sides of a conflicted lockfile", () => {
    const conflicted = `# yarn lockfile v1


<<<<<<< HEAD
mine@^1.0.0:
  version "1.0.0"
=======
theirs@^2.0.0:
  version "2.0.0"
>>>>>>> other
`;
    expect(parseYarnLock(conflicted)).to.deep.equal({
      "mine@^1.0.0": { version: "1.0.0" },
      "theirs@^2.0.0": { version: "2.0.0" }
    });
  });

  it("falls back to YAML when the lockfile grammar does not fit", () => {
    // upstream yarn uses js-yaml with FAILSAFE_SCHEMA here; fyn substitutes yamljs, so this
    // pins the one place the vendored parser diverges from yarn v1.22.22
    expect(parseYarnLock('# yarn lockfile v1\n\nbroken@^1.0.0:\n  : "no key"\n')).to.deep.equal({
      "broken@^1.0.0": ': "no key"'
    });
  });

  it("throws with the line and column when neither parser can read it", () => {
    let caught: Error | undefined;
    try {
      parseYarnLock("# yarn lockfile v1\n\na@^1:\n\t- [ {\n");
    } catch (err) {
      caught = err as Error;
    }
    expect(caught).to.be.an("error");
    expect(caught?.message).to.match(/Unknown token.*3:1 in lockfile/);
  });
});
